### PR TITLE
fix: plugins include spec files in distributed pkg

### PR DESCRIPTION
**Pull request by AgentEnder**
Both plugins include spec files in their distributed package. 

For more context see: https://github.com/nrwl/nx/issues/5563

### CODE REVIEW

**Comment by tinesoft** [comment]
Hi @AgentEnder ,

Thanks for this PR my friend, much appreciated! 👍🏾 

In the case of changes like that, affecting the whole workspace, you can remove the scope.
It becomes simply: `fix: plugins include spec files in distributed pkg`

(You can amend the commit and force push on this PR)

Thanks in advance!

**Comment by AgentEnder** [comment]
Great, thanks! That should be it now. As far as the failing tests go, they should not be related to this change correct?

**Comment by tinesoft** [comment]
Thanks for the update Craig.

Yes I don't think the failing tests are related to your changes...

Actually it's even weird that these tests were working at all !
They clearly need to be updated when running on a Windows machine...
I'm surprised that they didn't fail sooner...

I will investigate

**Comment by tinesoft** [comment]
OK, 

I've found why the tests were working before (or so I thought they were anyway...) :

Actually, the result displayed from the Github Actions jobs [were retrieved from the Nx' cloud cache](https://github.com/tinesoft/nxrocks/runs/2443380892?check_suite_focus=true#step:6:54)!
In fact, I always run the tests locally before pushing to remote. And on my mac os, it is working fine. 

I need to skip the cache when running on github actions. Of course the tests must be corrected as well.

Mystery resolved :-)

**Comment by AgentEnder** [comment]
@tinesoft rather than disabling the cache I would recommend playing around with the following:

https://nx.dev/latest/angular/core-concepts/computation-caching#runtime-cache-inputs

https://stackoverflow.com/questions/3466166/how-to-check-if-running-in-cygwin-mac-or-linux

The cloud cache in CI is a huge benefit, but it should be configured to ensure its not throwing false positives or negatives. I'm happy to help with those if needed.

**Comment by tinesoft** [comment]
Thanks for the proposed help Craig!
I managed to solve the caching issue without deactivating Nx Cloud  (7ca92571f3c75e97022e41544abae1c1481005c8) and I fixed the failing tests on Windows (357ddd563589bc31df1465438027e7bc330c7893).

**Comment by tinesoft** [comment]
Darn it! the caching issue is not resolved actually... 😞 

I've created https://github.com/tinesoft/nxrocks/issues/58 to continue the discussion there.
If your help offer still stand , ofcourse, I'd appreciate it!

**Comment by AgentEnder** [comment]
Hehe, I thought it might. Ill take a look at it when I get a chance, probably mid next week. In the meantime, those 2 links I sent earlier should give a good idea of what needs to be done.

**Pull request merged**
